// 标准拼豆色卡数据
// 1斤 = 500克

const mard221Colors = [
    // A组 - 黄色系列 (28色)
    {code: 'A01', name: '淡黄', stock: 0, unit: '克'},
    {code: 'A02', name: '浅黄', stock: 0, unit: '克'},
    {code: 'A03', name: '柠檬黄', stock: 0, unit: '克'},
    {code: 'A04', name: '嫩黄', stock: 0, unit: '克'},
    {code: 'A05', name: '明黄', stock: 0, unit: '克'},
    {code: 'A06', name: '中黄', stock: 0, unit: '克'},
    {code: 'A07', name: '金黄', stock: 0, unit: '克'},
    {code: 'A08', name: '橙黄', stock: 0, unit: '克'},
    {code: 'A09', name: '深黄', stock: 0, unit: '克'},
    {code: 'A11', name: '奶油黄', stock: 0, unit: '克'},
    {code: 'A12', name: '杏黄', stock: 0, unit: '克'},
    {code: 'A13', name: '土黄', stock: 0, unit: '克'},
    {code: 'A14', name: '芥末黄', stock: 0, unit: '克'},
    {code: 'A15', name: '橄榄黄', stock: 0, unit: '克'},
    {code: 'A16', name: '米黄', stock: 0, unit: '克'},
    {code: 'A17', name: '浅米黄', stock: 0, unit: '克'},
    {code: 'A18', name: '深米黄', stock: 0, unit: '克'},
    {code: 'A19', name: '金丝雀', stock: 0, unit: '克'},
    {code: 'A20', name: '橙橘', stock: 0, unit: '克'},
    {code: 'A21', name: '蜜桃黄', stock: 0, unit: '克'},
    {code: 'A22', name: '芒果黄', stock: 0, unit: '克'},
    {code: 'A23', name: '香蕉黄', stock: 0, unit: '克'},
    {code: 'A24', name: '向日葵', stock: 0, unit: '克'},
    {code: 'A25', name: '玉米黄', stock: 0, unit: '克'},
    {code: 'A26', name: '蛋黄', stock: 0, unit: '克'},
    {code: 'A27', name: '暖黄', stock: 0, unit: '克'},
    {code: 'A28', name: '暗黄', stock: 0, unit: '克'},

    // B组 - 绿色系列 (32色)
    {code: 'B01', name: '浅绿', stock: 0, unit: '克'},
    {code: 'B02', name: '薄荷绿', stock: 0, unit: '克'},
    {code: 'B03', name: '青绿', stock: 0, unit: '克'},
    {code: 'B04', name: '嫩绿', stock: 0, unit: '克'},
    {code: 'B05', name: '草绿', stock: 0, unit: '克'},
    {code: 'B06', name: '翠绿', stock: 0, unit: '克'},
    {code: 'B07', name: '森林绿', stock: 0, unit: '克'},
    {code: 'B08', name: '深绿', stock: 0, unit: '克'},
    {code: 'B09', name: '墨绿', stock: 0, unit: '克'},
    {code: 'B10', name: '橄榄绿', stock: 0, unit: '克'},
    {code: 'B11', name: '苔藓绿', stock: 0, unit: '克'},
    {code: 'B12', name: '灰绿', stock: 0, unit: '克'},
    {code: 'B13', name: '蓝绿', stock: 0, unit: '克'},
    {code: 'B14', name: '孔雀绿', stock: 0, unit: '克'},
    {code: 'B15', name: '海绿', stock: 0, unit: '克'},
    {code: 'B16', name: '湖绿', stock: 0, unit: '克'},
    {code: 'B17', name: '碧绿', stock: 0, unit: '克'},
    {code: 'B18', name: '玉绿', stock: 0, unit: '克'},
    {code: 'B19', name: '春绿', stock: 0, unit: '克'},
    {code: 'B20', name: '嫩芽绿', stock: 0, unit: '克'},
    {code: 'B21', name: '酸橙绿', stock: 0, unit: '克'},
    {code: 'B22', name: '柠檬绿', stock: 0, unit: '克'},
    {code: 'B23', name: '苹果绿', stock: 0, unit: '克'},
    {code: 'B24', name: '叶绿', stock: 0, unit: '克'},
    {code: 'B25', name: '草黄绿', stock: 0, unit: '克'},
    {code: 'B26', name: '灰橄榄', stock: 0, unit: '克'},
    {code: 'B27', name: '深橄榄', stock: 0, unit: '克'},
    {code: 'B28', name: '蕨绿', stock: 0, unit: '克'},
    {code: 'B29', name: '松绿', stock: 0, unit: '克'},
    {code: 'B30', name: '仙人掌绿', stock: 0, unit: '克'},
    {code: 'B31', name: '鼠尾草绿', stock: 0, unit: '克'},
    {code: 'B32', name: '暗绿', stock: 0, unit: '克'},

    // C组 - 蓝色系列 (28色)
    {code: 'C01', name: '浅蓝', stock: 0, unit: '克'},
    {code: 'C02', name: '天蓝', stock: 0, unit: '克'},
    {code: 'C03', name: '湖蓝', stock: 0, unit: '克'},
    {code: 'C04', name: '冰蓝', stock: 0, unit: '克'},
    {code: 'C05', name: '宝蓝', stock: 0, unit: '克'},
    {code: 'C06', name: '深蓝', stock: 0, unit: '克'},
    {code: 'C07', name: '海军蓝', stock: 0, unit: '克'},
    {code: 'C08', name: '靛蓝', stock: 0, unit: '克'},
    {code: 'C09', name: '孔雀蓝', stock: 0, unit: '克'},
    {code: 'C10', name: '青蓝', stock: 0, unit: '克'},
    {code: 'C11', name: '蔚蓝', stock: 0, unit: '克'},
    {code: 'C12', name: '钴蓝', stock: 0, unit: '克'},
    {code: 'C13', name: '群青', stock: 0, unit: '克'},
    {code: 'C14', name: '普鲁士蓝', stock: 0, unit: '克'},
    {code: 'C15', name: '藏青', stock: 0, unit: '克'},
    {code: 'C16', name: '灰蓝', stock: 0, unit: '克'},
    {code: 'C17', name: '浅灰蓝', stock: 0, unit: '克'},
    {code: 'C18', name: '中灰蓝', stock: 0, unit: '克'},
    {code: 'C19', name: '深灰蓝', stock: 0, unit: '克'},
    {code: 'C20', name: '午夜蓝', stock: 0, unit: '克'},
    {code: 'C21', name: '电光蓝', stock: 0, unit: '克'},
    {code: 'C22', name: '婴儿蓝', stock: 0, unit: '克'},
    {code: 'C23', name: '粉蓝', stock: 0, unit: '克'},
    {code: 'C24', name: '爱丽丝蓝', stock: 0, unit: '克'},
    {code: 'C25', name: '钢蓝', stock: 0, unit: '克'},
    {code: 'C26', name: '道奇蓝', stock: 0, unit: '克'},
    {code: 'C27', name: '皇家蓝', stock: 0, unit: '克'},
    {code: 'C28', name: '暗蓝', stock: 0, unit: '克'},

    // D组 - 紫色系列 (25色)
    {code: 'D01', name: '淡紫', stock: 0, unit: '克'},
    {code: 'D02', name: '浅紫', stock: 0, unit: '克'},
    {code: 'D03', name: '薰衣草', stock: 0, unit: '克'},
    {code: 'D04', name: '紫罗兰', stock: 0, unit: '克'},
    {code: 'D05', name: '中紫', stock: 0, unit: '克'},
    {code: 'D06', name: '紫色', stock: 0, unit: '克'},
    {code: 'D07', name: '深紫', stock: 0, unit: '克'},
    {code: 'D08', name: '暗紫', stock: 0, unit: '克'},
    {code: 'D09', name: '紫红', stock: 0, unit: '克'},
    {code: 'D10', name: '洋红', stock: 0, unit: '克'},
    {code: 'D11', name: '紫粉', stock: 0, unit: '克'},
    {code: 'D12', name: '蓝紫', stock: 0, unit: '克'},
    {code: 'D13', name: '靛紫', stock: 0, unit: '克'},
    {code: 'D14', name: '紫罗兰紫', stock: 0, unit: '克'},
    {code: 'D15', name: '葡萄紫', stock: 0, unit: '克'},
    {code: 'D16', name: '李子紫', stock: 0, unit: '克'},
    {code: 'D17', name: '紫罗兰蓝', stock: 0, unit: '克'},
    {code: 'D18', name: '紫水晶', stock: 0, unit: '克'},
    {code: 'D19', name: '紫丁香', stock: 0, unit: '克'},
    {code: 'D20', name: '紫藤', stock: 0, unit: '克'},
    {code: 'D21', name: '紫罗兰红', stock: 0, unit: '克'},
    {code: 'D22', name: '紫罗兰灰', stock: 0, unit: '克'},
    {code: 'D23', name: '紫罗兰深', stock: 0, unit: '克'},
    {code: 'D24', name: '紫罗兰浅', stock: 0, unit: '克'},
    {code: 'D25', name: '紫罗兰暗', stock: 0, unit: '克'},

    // E组 - 粉色系列 (24色)
    {code: 'E01', name: '淡粉', stock: 0, unit: '克'},
    {code: 'E02', name: '浅粉', stock: 0, unit: '克'},
    {code: 'E03', name: '粉红', stock: 0, unit: '克'},
    {code: 'E04', name: '玫红', stock: 0, unit: '克'},
    {code: 'E05', name: '玫瑰红', stock: 0, unit: '克'},
    {code: 'E06', name: '深粉', stock: 0, unit: '克'},
    {code: 'E07', name: '桃红', stock: 0, unit: '克'},
    {code: 'E08', name: '桃粉', stock: 0, unit: '克'},
    {code: 'E09', name: '珊瑚粉', stock: 0, unit: '克'},
    {code: 'E10', name: '西瓜粉', stock: 0, unit: '克'},
    {code: 'E11', name: '樱花粉', stock: 0, unit: '克'},
    {code: 'E12', name: '樱花', stock: 0, unit: '克'},
    {code: 'E13', name: '婴儿粉', stock: 0, unit: '克'},
    {code: 'E14', name: '粉紫', stock: 0, unit: '克'},
    {code: 'E15', name: '粉蓝', stock: 0, unit: '克'},
    {code: 'E16', name: '粉绿', stock: 0, unit: '克'},
    {code: 'E17', name: '粉黄', stock: 0, unit: '克'},
    {code: 'E18', name: '粉橙', stock: 0, unit: '克'},
    {code: 'E19', name: '粉灰', stock: 0, unit: '克'},
    {code: 'E20', name: '粉棕', stock: 0, unit: '克'},
    {code: 'E21', name: '粉红深', stock: 0, unit: '克'},
    {code: 'E22', name: '粉红浅', stock: 0, unit: '克'},
    {code: 'E23', name: '粉红暗', stock: 0, unit: '克'},
    {code: 'E24', name: '粉红灰', stock: 0, unit: '克'},

    // F组 - 红色系列 (25色)
    {code: 'F01', name: '淡红', stock: 0, unit: '克'},
    {code: 'F02', name: '浅红', stock: 0, unit: '克'},
    {code: 'F03', name: '橙红', stock: 0, unit: '克'},
    {code: 'F04', name: '橘红', stock: 0, unit: '克'},
    {code: 'F05', name: '朱红', stock: 0, unit: '克'},
    {code: 'F06', name: '大红', stock: 0, unit: '克'},
    {code: 'F07', name: '深红', stock: 0, unit: '克'},
    {code: 'F08', name: '暗红', stock: 0, unit: '克'},
    {code: 'F09', name: '酒红', stock: 0, unit: '克'},
    {code: 'F10', name: '紫红', stock: 0, unit: '克'},
    {code: 'F11', name: '洋红', stock: 0, unit: '克'},
    {code: 'F12', name: '玫红', stock: 0, unit: '克'},
    {code: 'F13', name: '玫瑰红', stock: 0, unit: '克'},
    {code: 'F14', name: '珊瑚红', stock: 0, unit: '克'},
    {code: 'F15', name: '西瓜红', stock: 0, unit: '克'},
    {code: 'F16', name: '番茄红', stock: 0, unit: '克'},
    {code: 'F17', name: '樱桃红', stock: 0, unit: '克'},
    {code: 'F18', name: '草莓红', stock: 0, unit: '克'},
    {code: 'F19', name: '石榴红', stock: 0, unit: '克'},
    {code: 'F20', name: '砖红', stock: 0, unit: '克'},
    {code: 'F21', name: '铁锈红', stock: 0, unit: '克'},
    {code: 'F22', name: '栗红', stock: 0, unit: '克'},
    {code: 'F23', name: '胭脂红', stock: 0, unit: '克'},
    {code: 'F24', name: '绯红', stock: 0, unit: '克'},
    {code: 'F25', name: '深绯红', stock: 0, unit: '克'},

    // G组 - 棕色系列 (21色)
    {code: 'G01', name: '浅棕', stock: 0, unit: '克'},
    {code: 'G02', name: '中棕', stock: 0, unit: '克'},
    {code: 'G03', name: '棕色', stock: 0, unit: '克'},
    {code: 'G04', name: '深棕', stock: 0, unit: '克'},
    {code: 'G05', name: '暗棕', stock: 0, unit: '克'},
    {code: 'G06', name: '咖啡', stock: 0, unit: '克'},
    {code: 'G07', name: '巧克力', stock: 0, unit: '克'},
    {code: 'G08', name: '可可', stock: 0, unit: '克'},
    {code: 'G09', name: '卡其', stock: 0, unit: '克'},
    {code: 'G10', name: '米色', stock: 0, unit: '克'},
    {code: 'G11', name: '驼色', stock: 0, unit: '克'},
    {code: 'G12', name: '沙色', stock: 0, unit: '克'},
    {code: 'G13', name: '土色', stock: 0, unit: '克'},
    {code: 'G14', name: '赭石', stock: 0, unit: '克'},
    {code: 'G15', name: '褐色', stock: 0, unit: '克'},
    {code: 'G16', name: '深褐色', stock: 0, unit: '克'},
    {code: 'G17', name: '灰棕', stock: 0, unit: '克'},
    {code: 'G18', name: '浅灰棕', stock: 0, unit: '克'},
    {code: 'G19', name: '深灰棕', stock: 0, unit: '克'},
    {code: 'G20', name: '红棕', stock: 0, unit: '克'},
    {code: 'G21', name: '黄棕', stock: 0, unit: '克'},

    // H组 - 黑色系列 (23色)
    {code: 'H01', name: '透明', stock: 0, unit: '克'},
    {code: 'H02', name: '白色', stock: 0, unit: '克'},
    {code: 'H03', name: '浅灰', stock: 0, unit: '克'},
    {code: 'H04', name: '中灰', stock: 0, unit: '克'},
    {code: 'H05', name: '灰色', stock: 0, unit: '克'},
    {code: 'H06', name: '深灰', stock: 0, unit: '克'},
    {code: 'H07', name: '黑色', stock: 0, unit: '克'},
    {code: 'H08', name: '深黑', stock: 0, unit: '克'},
    {code: 'H09', name: '银灰', stock: 0, unit: '克'},
    {code: 'H10', name: '银色', stock: 0, unit: '克'},
    {code: 'H11', name: '金色', stock: 0, unit: '克'},
    {code: 'H12', name: '铜色', stock: 0, unit: '克'},
    {code: 'H13', name: '青铜', stock: 0, unit: '克'},
    {code: 'H14', name: '铂金', stock: 0, unit: '克'},
    {code: 'H15', name: '米白', stock: 0, unit: '克'},
    {code: 'H16', name: '象牙白', stock: 0, unit: '克'},
    {code: 'H17', name: '奶油白', stock: 0, unit: '克'},
    {code: 'H18', name: '珍珠白', stock: 0, unit: '克'},
    {code: 'H19', name: '灰白', stock: 0, unit: '克'},
    {code: 'H20', name: '浅灰白', stock: 0, unit: '克'},
    {code: 'H21', name: '中灰白', stock: 0, unit: '克'},
    {code: 'H22', name: '深灰白', stock: 0, unit: '克'},
    {code: 'H23', name: '暗灰白', stock: 0, unit: '克'},

    // M组 - 低饱和色 (16色)
    {code: 'M01', name: '低饱和黄', stock: 0, unit: '克'},
    {code: 'M02', name: '低饱和橙', stock: 0, unit: '克'},
    {code: 'M03', name: '低饱和红', stock: 0, unit: '克'},
    {code: 'M04', name: '低饱和粉', stock: 0, unit: '克'},
    {code: 'M05', name: '低饱和紫', stock: 0, unit: '克'},
    {code: 'M06', name: '低饱和蓝', stock: 0, unit: '克'},
    {code: 'M07', name: '低饱和绿', stock: 0, unit: '克'},
    {code: 'M08', name: '低饱和青', stock: 0, unit: '克'},
    {code: 'M09', name: '低饱和棕', stock: 0, unit: '克'},
    {code: 'M10', name: '低饱和灰', stock: 0, unit: '克'},
    {code: 'M11', name: '低饱和米', stock: 0, unit: '克'},
    {code: 'M12', name: '低饱和卡其', stock: 0, unit: '克'},
    {code: 'M13', name: '低饱和橄榄', stock: 0, unit: '克'},
    {code: 'M14', name: '低饱和海军', stock: 0, unit: '克'},
    {code: 'M15', name: '低饱和酒红', stock: 0, unit: '克'},
    {code: 'M16', name: '低饱和墨绿', stock: 0, unit: '克'}
];

// 库存单位转换
const inventoryUnits = {
    JIN: {name: '斤', toGram: 500, fromGram: (g) => g / 500},
    GRAM: {name: '克', toGram: 1, fromGram: (g) => g},
    KILOGRAM: {name: '千克', toGram: 1000, fromGram: (g) => g / 1000}
};

// 默认配置
const defaultAppConfig = {
    shopName: '拼豆工作室',
    shopIcon: '',
    shopPhone: '',
    shopAddress: '',
    pricePerHour: 15,
    pricePerDay: 50,
    lowStockThresholdJin: 0.5,
    tableCount: 30,
    memberDiscount: 10,
    vipDiscount: 20,
    studentDiscount: 15,
    defaultInventoryUnit: '克',
    platformFees: {
        meituan: { name: '美团', feeRate: 15, enabled: true },
        douyin: { name: '抖音', feeRate: 18, enabled: true },
        dianping: { name: '大众点评', feeRate: 12, enabled: true },
        xiaohongshu: { name: '小红书', feeRate: 10, enabled: true },
        custom: { name: '其他平台', feeRate: 0, enabled: false }
    },
    presetStock: {},
    users: [
        { username: 'admin', password: 'admin123', role: 'admin', name: '管理员' },
        { username: 'user', password: 'user123', role: 'user', name: '普通员工' }
    ],
    costSharing: {
        enabled: false,
        partners: [
            { id: 1, name: '合伙人A', shareRatio: 50, enabled: true },
            { id: 2, name: '合伙人B', shareRatio: 50, enabled: true }
        ],
        sharingScope: 'revenue'
    }
};

function getBeadGroups() {
    return {
        A: mard221Colors.filter(c => c.code.startsWith('A')),
        B: mard221Colors.filter(c => c.code.startsWith('B')),
        C: mard221Colors.filter(c => c.code.startsWith('C')),
        D: mard221Colors.filter(c => c.code.startsWith('D')),
        E: mard221Colors.filter(c => c.code.startsWith('E')),
        F: mard221Colors.filter(c => c.code.startsWith('F')),
        G: mard221Colors.filter(c => c.code.startsWith('G')),
        H: mard221Colors.filter(c => c.code.startsWith('H')),
        M: mard221Colors.filter(c => c.code.startsWith('M'))
    };
}
